apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ib-gateway
  labels:
    app.kubernetes.io/name: ib-gateway
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: ib-gateway
